# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@e481e638abdb45e2fa30845305c387a544cc617f
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('src/test/**') }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
